config/routes.rb
Rails.application.routes.draw do
  get 'tasks/do_tasks' => 'tasks#do_tasks'
  get 'tasks/request_tasks' => 'tasks#request_tasks'
  post 'tasks/submit_task' => 'tasks#submit_task'
  get 'welcome/index'

  devise_for :users
  scope "/admin" do
    resources :users
    resources :tasks
  end

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.is?('user.user_admin')
      can :manage, User
    else
      can :read, User
    end
    if user.is?('user.user_admin')
      can :manage, Task
    else
      can :read, User
    end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :owner, :class_name => 'User'
  belongs_to :checker, :class_name => 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, :class_name => 'Task', foreign_key: 'owner_id'
  has_many :checked_tasks, :class_name => 'Task', foreign_key: 'checker_id'

  ROLES = %w[user.user_admin user.task_admin]

  def get_tasks(number)
    #byebug
    ctasks = unfinish_tasks(number)
    request_new_tasks(number-ctasks.count) if ctasks.count<number
    ctasks
  end

  def request_new_tasks(number=1)
    Task.transaction do
      Task.lock.where(owner: nil).limit(number).each do |tk|
        tk.owner = self
        tk.save
      end
    end
  end

    #find
    #where
    #limit
    #Task.transaction do
      #t = Task.lock.first
      #t.url = 'new'
      #t.save!
    #end
  def unfinish_tasks(number=1)
    ret = self.tasks.where(result: nil).limit(number)
      #if number
        #ret.limit(number)
  end
  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def is?(role)
    roles.include?(role.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def do_tasks
    @tasks = current_user.get_tasks 1 
  end

  def request_tasks
    #@condition = {}
    #@condition[:orgnization] = current_user.orginization unless current_user.orgnization == User::ORGS[0]
    #@condition[:status] = params[:status] if params[:status] and User::STATUS.include? params[:status]
    #params[:number]
    #@tasks = current_user.reuqest_new_tasks params[:number]
  end

  def submit_task
    #Rails.logger.info "***************"
    #Rails.logger.info task_params
    tparams = task_params
    @task = Task.find(tparams[:task_id])
    tparams.delete :task_id
    #Rails.logger.info @task
    @task.update(tparams)
    @task = current_user.request_new_tasks[0]
    respond_to do |format|
      format.html {
        #byebug
        redirect_to @task, notice: 'Task was successfully updated.' 
      }
      #format.json { render :show, status: :ok, location: @ntask }
      format.json { 
        render :json => @task
        #render :show, status: :ok, location: @task 
      }
    end
  end

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:task_id, :owner_id, :request_at, :finish_at, :result, :check_result, :checker_id, :check_at, :url, :number)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :zhifubao)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.haml
%footer
  -#.footer
  -#<small>
    -#The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    -#by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  -#</small>
  .container
    -#.center
      -#%p= t('common.record_info')
    %nav
      %ul.nav.navbar-nav.navbar-right
        -#%li= link_to t("common.about"), "#"
        -#%li= link_to t("common.contact"), "#"
        %li
          %a{"data-toggle"=> 'modal', "data-target"=> '#aboutModal'}= t('common.about')
        %li
          %a{"data-toggle"=> 'modal', "data-target"=> '#contactModal'}= t('common.contact')

-#%button{"data-toggle"=> 'modal', "data-target"=> '#aboutModal'}= t('common.about')
.modal.fade#aboutModal{"aria-labelledby" => 'aboutModalLabel', :role => "dialog"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{:type => "button", "data-dismiss" => "modal", "aria-label" => 'Close'}
          %span{"aria-hidden" => 'true'} &times;
        %h4= t("common.about_header")
      .modal-body
        %p= t('common.about_body')

.modal.fade#contactModal{"aria-labelledby" => 'contactModalLabel', :role => "dialog"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{:type => "button", "data-dismiss" => "modal", "aria-label" => 'Close'}
          %span{"aria-hidden" => 'true'} &times;
        %h4= t("common.contact_header")
      .modal-body
        %p= t('common.contact_body')

app/views/layouts/_header.html.haml
%header.navbar.navbar-inverse
  .container
    = link_to "TROLL", welcome_index_url, {id: "logo"}
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to t("common.task_administration"), tasks_url
        -unless current_user
          -#%li= link_to t("common.sign_up"), new_user_registration_url
          %li= link_to t("common.log_in"), new_user_session_url
          -if can? :manage, User
            %li= link_to t("user.admin"), users_url
        -if current_user
          %li= link_to current_user.email, edit_user_registration_url
          %li= link_to t("common.log_out"), destroy_user_session_path, method: :delete
        -#%li= link_to t("common.help"), "#"
  -#-if controller_name == "welcome"
    -#.container
      -#-#%div{"role"=>"tabpanel"}
      -#%ul#myTab.nav.nav-tabs{"role"=>"tablist"}
        -#%li.active{:role=>"presentation"}
          -#= link_to t("common.home"), "#home", {role: 'tab', "aria-controls"=>"home", "data-toggle"=> 'tab'}
        -#%li{:role=>"presentation"}
          -#=link_to t("user.profile"), "#profile", {role: 'tab', "aria-controls"=>"profile", "data-toggle"=>'tab'}
        -#-if current_user.is? 'user.user_admin'
          -#%li{:role=>"presentation"}
            -#= link_to t("user.admin"), "#useradmin", {role: 'tab', "aria-controls"=>"useradmin", "data-toggle"=>"tab"}
  -#.container
    -#%div{"role"=>"tabpanel"}
    -#%ul#myTab.nav.nav-tabs{"role"=>"tablist"}
      -#%li{:class=>("active" if controller_name == "welcome"), :role=>"presentation"}
        -#= link_to t("common.home"), welcome_index_url, {role: 'tab'}
      -#-#%li{:class=>("active" if controller_name == "results"), :role=>"presentation"}
        -#-#= link_to t("common.results"), results_url, {role: 'tab'}
      -#-#-if can? :manage, Match
      -#%li{:class=>("active" if controller_name == "matches"), :role=>"presentation"}
        -#= link_to t("common.matches"), matches_url, {role: 'tab'}
      -#%li{:class=>("active" if controller_name == "events"), :role=>"presentation"}
        -#= link_to t("common.events"), events_url, {role: 'tab'}
      -#-#-if can? :manage, Comment
        -#-#%li{:class=>("active" if controller_name == "comments"), :role=>"presentation"}
          -#-#= link_to t("common.comments"), comments_url, {role: 'tab'}
      -#-if can? :manage, LiveRoom
        -#%li{:class=>("active" if controller_name == "live_rooms"), :role=>"presentation"}
          -#= link_to t("common.live_room"), live_rooms_url, {role: 'tab'}
      -#-if can? :manage, User
        -#%li{:class=>("active" if controller_name == "users"), :role=>"presentation"}
          -#= link_to t("user.list"), users_url, {role: 'tab'}

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    -#%title= full_title(yield(:title))
    %title= yield(:title)
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:name => "viewport", :content=>"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"}
    -#<!--[if lt IE 9]>
      -#<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      -#</script>
    -#<![endif]-->
  -#%frameset
    -#%frame{"src"=>"http://www.ifeng.com"}

  %body
    = render "layouts/header"

    .container
      %p.notice= notice
      %p.alert= alert
      = yield

    = render "layouts/footer"
    
  

app/views/tasks/_form.html.haml
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :owner_id
    = f.number_field :owner_id
  .field
    = f.label :request_at
    = f.datetime_select :request_at
  .field
    = f.label :finish_at
    = f.datetime_select :finish_at
  .field
    = f.label :result
    = f.number_field :result
  .field
    = f.label :check_result
    = f.number_field :check_result
  .field
    = f.label :checker_id
    = f.number_field :checker_id
  .field
    = f.label :check_at
    = f.datetime_select :check_at
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/tasks/do_tasks.html.haml
-#.row
  -#.col-md-6.col-xs-6 
    -#=button_to "OK", {action: "submit_task"}, params: {id: 0, result: 0}, remote: true, form: {"data-type" => "json"}, class: 'btn-lg btn-primary work-btn'
  -#.col-md-4.col-xs-4 
    -#=button_to "OK", {action: "submit_task"}, params: {id: 0, result: 0}, remote: true, form: {"data-type" => "json"}, class: 'work-btn btn-lg btn-danger'
    -#-#=button_to "OK", {action: "submit_task"}, params: {id: 0, result: 1}, remote: true, form: {"data-type" => "json"}
    -#-#%span.glyphicon.glyphicon-thumbs-down
    -#-#%span.glyphicon.glyphicon-thumbs-up
  -#.col-md-2.col-xs-2 
    -#%span.glyphicon.glyphicon-ok
    -#-#%span.glyphicon.glyphicon-remove
-#-##carousel-example-generic.carousel.slide{"data-ride" => "carousel", "data-interval" => 0, "data-wrap" => "false", "data-keyboard"=>"true"}

#carousel-example-generic.carousel.slide{ "data-interval" => 0, "data-wrap" => "false", "data-keyboard"=>"true"}
  -#%ol.carousel-indicators
    -#%li.active{"data-target"=>"#carousel-example-generic", "data-slide-to" => "0"}
    -#%li.active{"data-target"=>"#carousel-example-generic", "data-slide-to" => "1"}
    -#%li.active{"data-target"=>"#carousel-example-generic", "data-slide-to" => "2"}

  #carousel-content.carousel-inner{role: "listbox"}
    -@tasks.each_with_index do |t, index|
      .item{:class=>("active" if index ==0 )}
        =image_tag(t.url, task_id: t.id)
    -#.item.active
      -#%img{alt: "first", src: "http://y1.ifengimg.com/a/2015_27/600f76858444336_size213_w1024_h681.jpg", "data-holder-rendered" => "true"}
      -#%img{alt: "first", src: "http://y1.ifengimg.com/a/2015_27/600f76858444336_size213_w1024_h681.jpg", task_id: '111'}
    -#.item
      -#%img{alt: "first", src: "http://y1.ifengimg.com/a/2015_20/876db9ede4ee79a_size27_w258_h258.jpg", "data-holder-rendered" => "true"}
    -#.item
      -#%img{alt: "first", src: "http://y2.ifengimg.com/a/2014_42/9b90289da8dc510.jpg", "data-holder-rendered" => "true"}
  
  %a#carousel-left-control.left.carousel-control.carousel-control-task{href: "#carousel-example-generic", role: "button", "data-slide" => "prev"}
    %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "false"}
      %span.sr-only Previous
  %a#carousel-right-control.right.carousel-control.carousel-control-task{href: "#carousel-example-generic", role: "button", "data-slide" => "next"}
    %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "false"}
      %span.sr-only Next
  -#%a.carousel-control-normal{href: "#carousel-example-generic", role: "button", "data-slide" => "prev"}
  %a#normal-pic-btn.carousel-control-normal{role: "button"}
  %a#unnormal-pic-btn.carousel-control-normal.unnormal{role: "button"}
  -##pic-status-tag.carousel-tag
    -#%span.glyphicon.glyphicon-ok
    -#%p normal

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %thead
    %tr
      %th Owner
      %th Request at
      %th Finish at
      %th Result
      %th Check result
      %th Checker
      %th Check at
      %th Url
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.owner_id
        %td= task.request_at
        %td= task.finish_at
        %td= task.result
        %td= task.check_result
        %td= task.checker_id
        %td= task.check_at
        %td= task.url
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Owner:
  = @task.owner_id
%p
  %b Request at:
  = @task.request_at
%p
  %b Finish at:
  = @task.finish_at
%p
  %b Result:
  = @task.result
%p
  %b Check result:
  = @task.check_result
%p
  %b Checker:
  = @task.checker_id
%p
  %b Check at:
  = @task.check_at
%p
  %b Url:
  = @task.url

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label t("user.email")
    = f.text_field :email, class: 'form-control', placeholder: t('user.email')

  .form-group
    = f.label t("user.name")
    = f.text_field :name, class: 'form-control', placeholder: t('user.name')

  .form-group
    = f.label t("user.authority")
    %br
    - for role in User::ROLES
      = check_box_tag "user[roles][#{role}]", role, @user.roles.include?(role), {name: "user[roles][]"}
      = label_tag "user_roles_#{role}", t(role)
      |
      -#%br
  = hidden_field_tag "user[roles][]"

  .form-group
    = f.label t("user.password")
    = f.password_field :password, class: "form-control", placeholder: t("user.password")
  .form-group
    = f.label t("user.password_confirmation")
    = f.password_field :password_confirmation, class: "form-control", placeholder: t("user.password_confirmation")

  .actions
    = f.submit t('user.save'), class: "btn btn-primary"

app/views/users/edit.html.haml
- provide :title, t("user.edit")
%h1= t("user.edit")+" "+@user.email

= render 'form'

.center
  = link_to t("user.show"), @user, class: "btn btn-default"
  \|
  = link_to t("user.back"), users_path, class: "btn btn-default"

app/views/users/index.html.haml
- provide :title, t("user.index")

%table.table.table-hover
  %thead
    %tr
      %th= t("user.email")
      %th= t("user.name")
      %th= t("user.created_at")
      -#%th= t("user.updated_at")
      -if can? :manage, User
        %th= t("user.operations")

  %tbody
    - @users.each do |user|
      %tr
        %td
          =link_to user_path(user) do
            =user.email
        %td= user.name
        %td= l user.created_at
        -#%td= l user.updated_at
        -if can? :manage, User
          %td
            %ul.list-inline
              %li= link_to t("user.edit"), edit_user_path(user)
              %li= link_to t("user.destroy"), user, method: :delete, data: {confirm: "Are you sure?"}

%br

-if can? :manage, User
  =link_to t("user.new"), new_user_path, class: "btn btn-lg btn-primary", role: "button"

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%h1= t("user.info")

.panel.panel-info
  .panel-heading= t('user.info')
  -#.panel-body
  %table.table.table-hover.table-bordered
    -#%thead
      -#%tr
        -#%th= t('user.info_name')
        -#%th= t('user.info_content')
    %tbody
      %tr
        %td= t('user.email')
        %td= @user.email
      %tr
        %td= t('user.name')
        %td= @user.name

.panel.panel-info
  .panel-heading= t('user.acr.src_authority')
  .panel-body
    - for role in User::ROLES
      = check_box_tag "user[src_roles][#{role}]", role, @user.roles.include?(role), {name: "user[src_roles][]", disabled: true}
      = label_tag "user_roles_#{role}", t(role)
      |

.center
  -if can? :manage, User
    = link_to t("user.edit"), edit_user_path(@user), class: "btn btn-default"
    -#\|
  -#= link_to t("user.back"), users_path, class: "btn btn-default"

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml